[build]
  command = 'npm run build'
  publish = 'build'
  functions = 'src/functions'

[dev]
  command = 'npm run start'


[[redirects]]
  from = '/gay'
  to = '/.netlify/functions/gay'
  status = 200

[[redirects]]
  from = '/random'
  to = '/.netlify/functions/random'
  status = 200

[[redirects]]
  from = '/gay.jpg'
  to = '/gay'

[[redirects]]
  from = '/random.jpg'
  to = '/random'
